### ISSUE TITLE
【immer plugin】Compatible problem!

### ISSUE THREAD

**Issue by Jemair** [rematch/rematch#567]
plugin version:
        "@rematch/core": "^1.0.0-beta.4",
        "@rematch/immer": "^1.0.2",

On some high version android webview, it will throw these error below. mostly occurs on huawei and meizu, system versions cover from android 7 ~ 8.1

pages runs well on system's native browser

```
TypeError: r is not a function

at t.(anonymous function) (http://h2.bilibili.com/1.space.local.js:47766:15693)
at http://h2.bilibili.com/1.space.local.js:47766:13107
at Array.forEach (<anonymous>)
at http://h2.bilibili.com/1.space.local.js:47766:13064
at Object.combineReducers (http://h2.bilibili.com/1.space.local.js:47766:13974)
at i (http://h2.bilibili.com/1.space.local.js:47766:15775)
at e.mergeReducers (http://h2.bilibili.com/1.space.local.js:47739:144)
at e.createRootReducer (http://h2.bilibili.com/1.space.local.js:47744:9)
at e.o.call.redux (http://h2.bilibili.com/1.space.local.js:47746:12)
at e.init (http://h2.bilibili.com/1.space.local.js:47747:34)
```
![image](https://user-images.githubusercontent.com/20502467/48124654-cd88fe80-e2b7-11e8-8ea2-0f5991d87e06.png)

i will continue to dig whether it is a rematch/immer problem or immer's

**Comment by Jemair** [comment]
found it's a rematch/immer's bug
