### ISSUE TITLE
immerPlugin of @rematch/immer doesn't work

### ISSUE THREAD

**Issue by frontend-is-magic** [rematch/rematch#991]
**Describe the bug**

Cannot use immerPlugin of @rematch/immer

**To Reproduce**

1. Create a vite-react project
2. Install packages using `yarn add @reduxjs/toolkit react-redux @rematch/core immer @rematch/immer`
3. Follow steps in Getting Started - Installation and Plugins - @rematch/immer of Rematch official website
4. Input your codes like:
```javascript
import {init} from "@rematch/core"
import {count} from './models.js'
import immerPlugin from "@rematch/immer"

const store = init({models: {count}, plugins: [immerPlugin()]})
export default store
```
6. You will see error logs as follow:
```
✘ [ERROR] No matching export in "node_modules/immer/dist/immer.mjs" for import "default"

    node_modules/@rematch/immer/dist/immer.esm.js:1:7:
      1 │ import produce from 'immer';
        ╵        ~~~~~~~

6:35:08 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@rematch/immer/dist/immer.esm.js:1:7: ERROR: No matching export in "node_modules/immer/dist/immer.mjs" for import "default"
    at failureErrorWithLog (/Users/myName/WebstormProjects/rematch-demo/node_modules/esbuild/lib/main.js:1472:15)
    at /Users/myName/WebstormProjects/rematch-demo/node_modules/esbuild/lib/main.js:945:25
    at /Users/myName/WebstormProjects/rematch-demo/node_modules/esbuild/lib/main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Expected behavior**

<img width="805" alt="where it comes from" src="https://github.com/user-attachments/assets/27a98a8c-e3ba-44b6-86b1-31f1aba5ceab">

<img width="1093" alt="error-log" src="https://github.com/user-attachments/assets/c87a65c6-64ba-4108-a6e9-45fe02a6f94f">

**Desktop**

- macOS
- chrome

**Additional context**

**Comment by frontend-is-magic** [comment]
I discovered that this issue was solved in pr #985 , please just release this new version of @rematch/immer
